### ISSUE TITLE
Roon client cannot see roon core through a wireguard tunnel using udp-proxy-2020 on both vpn endpoints

### ISSUE THREAD

**Issue by kevindd992002** [synfinatic/udp-proxy-2020#99] opened 2022-06-02 16:58 UTC
As mentioned [here](https://community.roonlabs.com/t/talking-to-roon-from-another-vlan-i-got-it-working/119840/112?u=kevin_mychal_ong), I have udp-proxy-2020 running on both VPN endpoints already but the roon client that runs on one side of the tunnel still doesn't see the roon core that's running on the other side of the tunnel.

As instructed, attached are the pcap files from both sides:

[pcap_serverside.zip](https://github.com/synfinatic/udp-proxy-2020/files/8825969/pcap_serverside.zip)
[pcap_clientside.zip](https://github.com/synfinatic/udp-proxy-2020/files/8825970/pcap_clientside.zip)
.

**Comment by synfinatic** [comment] 2022-06-02 18:14
Okay, I see your Roon Client sending packets, but udp-proxy-2020 isn't forwarding packets.  Most likely because it hasn't learned about the network on the other end yet.   

To fix that, on the client side udp-proxy-2020 arguments, add `--fixed-ip tun_wg0@<ip address>`

where the `<ip address>` is the IP address of the tun_wg0 interface of the pfSense box at the other end of the VPN tunnel (server side).  

I believe that should work.

**Comment by kevindd992002** [comment] 2022-06-03 09:49
I did that and it didn't work. Here's another set of pcap files with the `fixed-ip` argument in the client side udp-proxy-2020 arguments.

[pcap_clientside.zip](https://github.com/synfinatic/udp-proxy-2020/files/8831429/pcap_clientside.zip)
[pcap_serverside.zip](https://github.com/synfinatic/udp-proxy-2020/files/8831428/pcap_serverside.zip)

**Comment by synfinatic** [comment] 2022-06-03 14:57
So I see the Roon Discovery messages going over the VPN tunnel on the client side, but nothing is showing up on the server side of the VPN.   I'm guessing Wireguard is dropping packets on the floor because of how you have things configured.... that doesn't make your config "wrong" just what it is.  

What I would try instead is specifying the IP address of your Roon Core.... assuming it has a static IP.   Even if you are using DHCP, pfSense will allow you to assign a static IP address for a client.

You can also try using the broadcast address for your server side igb.10 network.  Typically would end in `.255` so something like `192.168.1.255`.

**Comment by kevindd992002** [comment] 2022-06-03 16:02
Are you saying use either the IP address of my Roon Core (it has a static reservation, yes) or the igb.10 broadcast network (192.168.10.255) on the `fixed-ip` argument on the udp-proxy-2020 service on the client side? Just making sure I got that correctly.

**Comment by synfinatic** [comment] 2022-06-03 16:03
correct.  Try the roon core IP first.

**Comment by kevindd992002** [comment] 2022-06-03 16:07
Ok, I'm trying now. When udp-proxy-2020 forwards the packet over the VPN tunnel, what is the source and destination IP of the packet?

**Comment by kevindd992002** [comment] 2022-06-03 16:17
I tried both and it still doesn't work. Here are the pcap files:

[pcap3_clientside.zip](https://github.com/synfinatic/udp-proxy-2020/files/8834078/pcap3_clientside.zip)
[pcap3_serverside.zip](https://github.com/synfinatic/udp-proxy-2020/files/8834079/pcap3_serverside.zip)
[pcap4_serverside.zip](https://github.com/synfinatic/udp-proxy-2020/files/8834081/pcap4_serverside.zip)
[pcap4_clientside.zip](https://github.com/synfinatic/udp-proxy-2020/files/8834082/pcap4_clientside.zip)

pcap3 is when `fixed-ip` equals `tun_wg0@192.168.10.17`
pcap4 is when `fixed-ip` equals `tun_wg0@192.168.10.255`

**Comment by synfinatic** [comment] 2022-06-03 20:01
So the problem is the same... the server side never sees the packets.    That would indicate to me that your VPN tunnel is "up", but not able to pass traffic because of some Wireguard or system configuration issue.

**Comment by kevindd992002** [comment] 2022-06-04 00:29
Yeah, but it does pass traffic. Let me show you some ping snapshots.

Client side:
LAN -> 192.168.20.0/24
WG interface IP -> 10.0.3.2
Ping test client -> 192.168.20.210

Server side:
LAN -> 192.168.10.0/24
WG interface IP -> 10.0.3.1
Roon Core IP -> 192.168.10.17

Ping from client to server:

![image](https://user-images.githubusercontent.com/3907957/171969193-9ae3b255-2b60-4cd6-b7d7-a862e2112574.png)

Ping from server to client pfsense interface IP (this SSH session to the server was even done from the client side):

![image](https://user-images.githubusercontent.com/3907957/171969253-a6bb860c-101d-4ffc-88e7-beefc84eff18.png)

Again though, what should the source and destination IP's of the packet be when it arrives on the server side after being forwarded by udp-proxy-2020?

**Comment by synfinatic** [comment] 2022-06-04 01:11
The source IP should be the Roon Client IP (appears to be 192.168.20.25).  The destination IP is any IP that will be forwarded across the VPN tunnel.  

The problem is the packet is not being forwarded, so the server side udp-proxy-2020 can't see it.  If you look at all the server side pcaps in Wireshark, you'll see they are empty (24bytes is an empty pcap file).  

I know Wireguard + pfSense works... because that's what I personally use at home.  However, I don't have a site-to-site VPN, but that shouldn't matter.  site-to-site or site-to-device VPN's are still at the end of the day Wiregard + pfSense.


The only idea i have right now is that you are using NAT on the client pfSense box to traverse the VPN.  udp-proxy-2020 packets won't get NAT'd and the way Wireguard works, that could cause them to not be forwarded over the VPN.  This is one thing I really hate about Wireguard- there is basically no logging or debugging when things don't work :(

The other thing is run tcpdump on the two firewalls, sniff the `tun_wg0` interface and do your ping again to generate traffic.  Then I can see what is being sent over the VPN tunnel and get a better idea of what your systems are doing.  something like:

`tcpdump -ni tun_wg0 -s0 -w client.pcap`

Anyways, take your time... I probably won't be available for a few days.

**Comment by kevindd992002** [comment] 2022-06-04 01:37
I see. What do you mean by "any IP that will be forwarded across the VPN tunnel"? Will udp-proxy-2020 on the server side (if it sees the packet in question) forward it to the server side LAN broadcast address as well?

These are the only outbound NAT/SNAT entries I have for the WF interface in the client side and these are used for unbound DNS domain overrides for the server side domain. And since the source IP is the Roon Client IP (and not localhost), these SNAT entries shouldn't really have an effect unless I'm missing something?

![image](https://user-images.githubusercontent.com/3907957/171971280-c9b206c3-550f-4f8a-9d45-dc92a1a03793.png)

Here are the tcpdump pcap files while I'm doing the same ping:

[pcap_tcpdump.zip](https://github.com/synfinatic/udp-proxy-2020/files/8836588/pcap_tcpdump.zip)

**Comment by synfinatic** [comment] 2022-06-04 03:08
Based on your info, I don't see anything _wrong_... things look like it _should_ work to me.  I'll have to think about how I might be able to reproduce this, but probably going to take a while.

**Comment by kevindd992002** [comment] 2022-06-04 03:24
> Based on your info, I don't see anything _wrong_... things look like it _should_ work to me. I'll have to think about how I might be able to reproduce this, but probably going to take a while.

Ok :( I really want to get this working. Thanks for the help, btw. I appreciate it.

When I do a packet capture from the client side pfsense GUI and filter port 9003 while running the roon client, I'm not seeing any hits being capture though. Does udp-proxy-2020 intercept the broadcast traffic before it hits the pfsense interface or something?

**Comment by synfinatic** [comment] 2022-06-05 22:36
I've never used the packet capture feature in pfSense, but it definitely should show the packets.  The only reason I can think it wouldn't show any packets is that it is filtering on TCP port 9003 instead of the UDP port.

**Comment by synfinatic** [comment] 2022-06-11 16:30
So looking at the pcaps for igb0, i see something I've never seen before and appears to be the root cause of this.

First, the pcap of packets going OUT of igb0 is empty.  This basically makes no sense, because it indicates that udp-proxy-2020 didn't send any packets out of that interface.

Second, the pcap showing packets coming INTO igb0 has a bunch of packets:

<img width="1144" alt="Screen Shot 2022-06-11 at 9 24 05 AM" src="https://user-images.githubusercontent.com/1075352/173196326-2beadcdc-e8a2-4120-a2c5-46ef5801de73.png">

But notice the destination address is the broadcast address is your Wireguard network, not the network I understood to be for igb0.

So something is really wonky with your setup.  can you provide the output / file contents of:

 1. running `ifconfig` on both your firewalls
 2. running `netstat -rn` on both your firewalls
 3. contents of `/usr/local/etc/udp-proxy-2020.conf` on both your firewalls

**Comment by synfinatic** [comment] 2023-03-19 22:28
will close this ticket if I don't hear back.

**Closed** 2023-10-20 16:25 UTC
